config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings do
    resources :orders
  end
  get 'pages/about'
  get 'pages/contact'

  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "/images/default.jpg"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	validates :name, :description, :price, presence: true
   	validates :price, numericality: { greater_than: 0 }
   	validates_attachment_presence :image

   	belongs_to :user
   	has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :address, :city, :state, presence: true

	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  before_filter :check_user, only: [:edit]

  # GET /listings
  # GET /listings.json

  def seller
    @listings = Listing.where(user: current_user)
  end

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    if current_user.recipient.blank?
      Stripe.api_key = ENV["STRIPE_API_KEY"]
      token = params[:stripeToken]

      recipient = Stripe::Recipient.create(
        :name => current_user.name,
        :type => "individual",
        :bank_account => token
        )

      current_user.recipient = recipient.id
      current_user.save
   end

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /orders
  # GET /orders.json

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => "usd",
        :card => token
        )
      flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    transfer = Stripe::Transfer.create(
      :amount => (@listing.price * 95).floor,
      :currency => "usd",
      :recipient => @seller.recipient
      )

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<h5>Copy right 2015</h5>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mall</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Manage Listings", seller_path %></li>
            <li><%= link_to "Sales History", sales_path %></li>
          </ul>
        </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Purchase History", purchases_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><a href="/users/sign_up">Sign Up</a></li>
          <li><a href="/users/sign_in">Sign In</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mall</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>

<%= render "/layouts/header" %>

<div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

	<%= yield %>

	<%= render "/layouts/footer" %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for (@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <br>

  <% if current_user.recipient.blank? %>
    <h1>Bank Accout Information</h1>

    <div class="form-group">
      <%= label_tag :country %>
      <%= text_field_tag :country, nil, {:name => nil, :'data-stripe' => "country", class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= label_tag :routing_number %>
      <%= text_field_tag :routing_number, nil, {:name => nil, :'data-stripe' => "routingNumber", class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= label_tag :account_number %>
      <%= text_field_tag :account_number, nil, {:name => nil, :'data-stripe' => "accountNumber", class: "form-control"} %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>Banner</h1>
</div>


<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>
        <div class="caption center">
          <h4><%= listing.name %></h4>
          <h5><%= number_to_currency(listing.price) %></h5>
          <%= "Sold by #{listing.user.name}" %>
          <br>
          <% if current_user == listing.user %>
            <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>
            <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: {no_turbolink: true} %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link", data: {no_turbolink: true} %>

app/views/listings/seller.html.erb
<div class="center">
	<h1>Manage Listings</h1>

	<table class="table table-striped table-bordered">
	  <tr>
	  	<th class="center">Image</th>
	  	<th class="center">Name</th>
	  	<th class="center">Description</th>
	  	<th class="center">Price</th>
	  	<th class="center">Action</th>
	  </tr>
	  <% @listings.each do |listing| %>
	  	<tr>
	  		<td><%= image_tag listing.image.url(:thumb) %></td>
	  		<td><%= listing.name %></td>
	  		<td><%= listing.description %></td>
	  		<td><%= number_to_currency(listing.price) %></td>
	  		<td>
	  			<div class="btn-group">
				  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				    Action <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu">
				    <li><%= link_to 'View', listing, class: "btn btn-link" %></li>
				    <li><%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %></li>
				    <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
				  </ul>
				</div>
	  		</td>
	  	</tr>
	  <% end %>
	</table>
</div>

<br>
<% if user_signed_in? %>
	<%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: {no_turbolink: true} %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
  </div>
  <div class="col-md-6">
    	<h3><%= @listing.name %></h3><br>
    	<%= @listing.description %><br>
    	<%= number_to_currency(@listing.price) %><br>
     <div class="center">
      <%= link_to 'Buy It Now', new_listing_order_path(@listing), class: "btn btn-primary", data: {no_turbolink: true} %>
     </div>
  </div>
</div>

<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3><br>
    <%= number_to_currency(@listing.price) %>
  </div>
  <div class="col-md-8">
    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state, class: "form-control" %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :number, "Credit Card Number" %>
            <%= text_field_tag :number, nil, {:name => nil, :'data-stripe' => "number", class: "form-control"} %>
          </div>
          <div class="col-md-4">
            <%= label_tag :cvc, "CVC" %>
            <%= text_field_tag :cvc, nil, {:name => nil, :'data-stripe' => "cvc", class: "form-control"} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, {use_two_digit_numbers: true}, {:name => nil, :'data-stripe' => 'exp-month', class: "form-control"} %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, {:name => nil, :'data-stripe' => 'exp-year', class: "form-control"} %>
          </div>
        </div>
      </div>

      <br>

      <div class="form-group">
        <%= f.submit "Complete Order", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listing_path(@listing) %>

app/views/orders/purchases.html.erb
<div class="center">
	<h1>Your Purchases History</h1>
</div>

<table class="table table-striped table-bordered">
  <tr>
  	<th class="center">Image</th>
	<th class="center">Name</th>
	<th class="center">Price</th>
	<th class="center">Seller</th>
	<th class="center">Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
	<tr>
	  <td><%= image_tag order.listing.image.url(:thumb) %></td>
	  <td><%= order.listing.name %></td>
	  <td><%= number_to_currency(order.listing.price) %></td>
	  <td><%= order.seller.name %></td>
	  <td><%= order.created_at.strftime("%B %-d, %Y") %></td>
	</tr>
  <% end %>
</table>

app/views/orders/sales.html.erb
<div class="center">
	<h1>Your Sales History</h1>

	<table class="table table-striped table-bordered">
	  <tr>
	  	<th class="center">Image</th>
	  	<th class="center">Name</th>
	  	<th class="center">Price</th>
	  	<th class="center">Customer</th>
	  	<th class="center">Date Sold</th>
	  </tr>
	  <% @orders.each do |order| %>
	  	<tr>
	  		<td><%= image_tag order.listing.image.url(:thumb) %></td>
	  		<td><%= order.listing.name %></td>
	  		<td><%= number_to_currency(order.listing.price) %></td>
	  		<td><%= order.buyer.name %></td>
	  		<td><%= order.created_at.strftime("%B %-d, %Y") %></td>
	  	</tr>
	  <% end %>
	</table>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>